{
    'name': 'Theme Louma',
    'category': 'Theme/Ecommerce',
    'sequence': 1,
    'summary': 'Html5 Responsive E-Commerce Multi-Purpose Theme including event and blog',
    'website': 'www.dev-talents.com',
    'version': '1.0',
    'author':'DevTalents',
    'description': """
 Html5 Responsive E-Commerce Multi-Purpose Theme including event and blog
==================

        """,
    'depends': [
        'website',
        'website_crm',
        'web',
        'auth_signup',
        'website_sale',
        'website_blog',
        'website_event',
        
        'website_product_video',
        'dynamic_mega_menu',
        'product_brand',
        'home_shop_adds',
        'snippet_google_map',
        'website_animate',
        'add_field_blog',
        'theme_common',
        'add_fields_event',
        'website_product_brand',
    ],
    'data': [
        'views/assets.xml',
        'views/menu.xml',
        'views/footer.xml',
        'views/page_about_us.xml',
        'views/page_about_us_1.xml',
        'views/page_about_us_2.xml',
        'views/page_about_us_3.xml',
        'views/page_404.xml',
        'views/page_coming_soon.xml',
        'views/page_login.xml',
        'views/page_contact.xml',
        'views/page_faq.xml',
        'views/page_signup.xml',
        'views/page_portfolio_2col.xml',
        'views/page_portfolio_3col.xml',
        'views/page_portfolio_4col.xml',
        'views/page_portfolio_list_image.xml',
        'views/page_portfolio_item.xml',
        'views/page_portfolio_slider.xml',
        'views/page_services.xml',
        'views/page_invoice.xml',
        'views/page_about_me.xml',
        'views/page_terms.xml',
        'views/page_testimonials.xml',
        'views/page_home.xml',
        'views/page_home_1.xml',
        'views/page_home_2.xml',
        'views/page_home_3.xml',
        'views/page_home_4.xml',
        'views/page_home_video.xml',
        'views/page_home_shop.xml',
        'views/page_pricing_tables_1.xml',
        'views/page_pricing_tables_2.xml',
        'views/page_pricing_tables_3.xml',
        'views/page_team.xml',
        'views/page_eventlist.xml',
        'views/customize_modal.xml',
        'views/snippets_option.xml',
        'views/snippets.xml',
        'views/blog.xml',
        'views/shop.xml',

    ],
    'images': ['static/description/main_screenshot.png'],
    'price': '150',
    'currency':'EUR',
    'live_test_url':'http://theme-louma.dev-talents.com/',
    'installable': True,
    'application': True,
}
